### ISSUE TITLE
Issue with testing.

### ISSUE THREAD

**Issue by gravyflex** [gizmoguy/notifybot#1]
I keep getting this error. Not sure how to resolve:

user@host:/usr/local/bin# ./notifybot.py user@domain.lan "Test"
Traceback (most recent call last):
  File "./notifybot.py", line 56, in <module>
    main()
  File "./notifybot.py", line 31, in main
    jid = xmpp.protocol.JID(config.get('xmpp', 'jid'))
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'jid' in section: 'xmpp'

**Comment by gizmoguy** [comment]
Hi gravyflex,

To me that sounds like notifybot is unable to find a configuration file with all the options defined.

Can you confirm that one of /etc/notifybot.cfg or ~/.notifybot.cfg or ./notifybot.cfg exists and it's contents look like notifybot.cfg.example.

Cheers,
Brad
